/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Measurements = IDL.Record({
  'hip' : IDL.Float64,
  'bust' : IDL.Float64,
  'length' : IDL.Float64,
  'waist' : IDL.Float64,
});
export const PatternPiece = IDL.Record({
  'name' : IDL.Text,
  'instructions' : IDL.Text,
  'cutOnFold' : IDL.Bool,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'hip' : IDL.Float64,
  'bust' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'length' : IDL.Float64,
  'phone' : IDL.Text,
  'waist' : IDL.Float64,
});
export const GarmentType = IDL.Record({
  'patternPieces' : IDL.Vec(PatternPiece),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'hip' : IDL.Float64,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'bust' : IDL.Float64,
  'createdAt' : IDL.Int,
  'garmentName' : IDL.Text,
  'length' : IDL.Float64,
  'notes' : IDL.Text,
  'waist' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Text],
      [],
    ),
  'calculatePattern' : IDL.Func(
      [IDL.Text, Measurements],
      [IDL.Vec(IDL.Tuple(PatternPiece, Measurements))],
      ['query'],
    ),
  'createGarment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(PatternPiece)],
      [],
      [],
    ),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteGarment' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getGarment' : IDL.Func([IDL.Text], [GarmentType], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listGarments' : IDL.Func([], [IDL.Vec(GarmentType)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listOrdersByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'updateCustomer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Bool],
      [],
    ),
  'updateGarment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(PatternPiece)],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Measurements = IDL.Record({
    'hip' : IDL.Float64,
    'bust' : IDL.Float64,
    'length' : IDL.Float64,
    'waist' : IDL.Float64,
  });
  const PatternPiece = IDL.Record({
    'name' : IDL.Text,
    'instructions' : IDL.Text,
    'cutOnFold' : IDL.Bool,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'hip' : IDL.Float64,
    'bust' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'length' : IDL.Float64,
    'phone' : IDL.Text,
    'waist' : IDL.Float64,
  });
  const GarmentType = IDL.Record({
    'patternPieces' : IDL.Vec(PatternPiece),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'hip' : IDL.Float64,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'bust' : IDL.Float64,
    'createdAt' : IDL.Int,
    'garmentName' : IDL.Text,
    'length' : IDL.Float64,
    'notes' : IDL.Text,
    'waist' : IDL.Float64,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Text],
        [],
      ),
    'calculatePattern' : IDL.Func(
        [IDL.Text, Measurements],
        [IDL.Vec(IDL.Tuple(PatternPiece, Measurements))],
        ['query'],
      ),
    'createGarment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(PatternPiece)],
        [],
        [],
      ),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteGarment' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getGarment' : IDL.Func([IDL.Text], [GarmentType], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listGarments' : IDL.Func([], [IDL.Vec(GarmentType)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listOrdersByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'updateCustomer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Bool],
        [],
      ),
    'updateGarment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(PatternPiece)],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };