/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : string,
  'hip' : number,
  'bust' : number,
  'name' : string,
  'createdAt' : bigint,
  'length' : number,
  'phone' : string,
  'waist' : number,
}
export interface GarmentType {
  'patternPieces' : Array<PatternPiece>,
  'name' : string,
  'description' : string,
}
export interface Measurements {
  'hip' : number,
  'bust' : number,
  'length' : number,
  'waist' : number,
}
export interface Order {
  'id' : string,
  'hip' : number,
  'customerName' : string,
  'status' : string,
  'bust' : number,
  'createdAt' : bigint,
  'garmentName' : string,
  'length' : number,
  'notes' : string,
  'waist' : number,
}
export interface PatternPiece {
  'name' : string,
  'instructions' : string,
  'cutOnFold' : boolean,
}
export interface _SERVICE {
  'addCustomer' : ActorMethod<
    [string, string, number, number, number, number],
    string
  >,
  'calculatePattern' : ActorMethod<
    [string, Measurements],
    Array<[PatternPiece, Measurements]>
  >,
  'createGarment' : ActorMethod<
    [string, string, Array<PatternPiece>],
    undefined
  >,
  'createOrder' : ActorMethod<
    [string, string, number, number, number, number, string],
    string
  >,
  'deleteCustomer' : ActorMethod<[string], boolean>,
  'deleteGarment' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], boolean>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getGarment' : ActorMethod<[string], GarmentType>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listGarments' : ActorMethod<[], Array<GarmentType>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listOrdersByStatus' : ActorMethod<[string], Array<Order>>,
  'updateCustomer' : ActorMethod<
    [string, string, string, number, number, number, number],
    boolean
  >,
  'updateGarment' : ActorMethod<
    [string, string, Array<PatternPiece>],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];